services:
  db:
    image: postgres:16
    container_name: taskmanager_db
    environment:
      POSTGRES_DB: taskmanager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata_taskmanager:/var/lib/postgressql/data

volumes:
  pgdata_taskmanager:
